
services:
  postgres:
    image: postgres:15-alpine  # Imagem leve do PostgreSQL
    container_name: projeto_db  # Nome do container
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}       # vindo do env
      POSTGRES_USER: ${DB_USER}     # vindo do env
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # vindo do env
    ports:
      - "5432:5432"  # Porta: host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência dos dados

volumes:
  postgres_data:  # Volume nomeado para não perder dados ao parar o container